[package]
name        = "simrs-jcasm-jacc"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "JavaCard applet compiler -- proc-macro frontend for jcapplet!{}"

[lib]
proc-macro = true

[dependencies]
proc-macro2    = "1"
syn            = { version = "2", features = ["full", "extra-traits"] }
quote          = "1"
simrs-jccompile = { workspace = true }

[dev-dependencies]
simrs-jcvm = { workspace = true }

[lints]
workspace = true
