[package]
name        = "simrs-ota"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "OTA secured packet structure per ETSI TS 102 225 / TS 102 226 -- no_std"

[features]
default = []
std     = []
ct-validation = []

[dependencies]
simrs-rijndael  = { workspace = true }
simrs-des       = { workspace = true }
simrs-iso7816   = { workspace = true }
simrs-consttime = { workspace = true }
simrs-secret    = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
simrs-consttime-validation = { workspace = true }

[lints]
workspace = true
