[package]
name        = "simrs-comp128"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "COMP128v1 (A3/A8) GSM authentication algorithm -- no_std, no_alloc"

[features]
default = []
std     = []
ct-validation = []

[dependencies]
simrs-consttime = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
simrs-consttime-validation = { workspace = true }

[lints]
workspace = true
