[package]
name        = "simrs-qemu"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "QEMU virtual smart card integration (shmem) -- std"

[features]
default = []

[dependencies]
simrs-sim             = { workspace = true, features = ["usim", "gsm"] }
simrs-transport-shmem = { workspace = true }

[dev-dependencies]
simrs-fs        = { workspace = true }
simrs-pin       = { workspace = true }
simrs-gsm       = { workspace = true }
simrs-usim      = { workspace = true }
simrs-milenage  = { workspace = true }
simrs-proactive = { workspace = true }
simrs-iso7816   = { workspace = true }
simrs-comp128   = { workspace = true }

[lints]
workspace = true
