[package]
name = "simrs-jacc"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "jacc -- JavaCard-Approximately-Compatible Compiler. Accepts .java/.jva source and .class/.jvc classfiles, produces .cap output."

[[bin]]
name = "simrs-jacc"
path = "src/main.rs"

[lib]
name = "simrs_jacc"
path = "src/lib.rs"

[dependencies]
simrs-jccompile = { workspace = true, features = ["std"] }
simrs-jcvm       = { workspace = true }

[dev-dependencies]
simrs-jcasm = { workspace = true }
simrs-jcvm  = { workspace = true }
proptest    = { workspace = true }

[lints]
workspace = true
