[package]
name        = "simrs-jcsl"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Oracle Java Card Simulator (jcsl) client, configurator, and process manager"
publish     = false

[dependencies]
simrs-transport = { workspace = true }
memfd            = "0.6"

[dev-dependencies]
insta = { workspace = true }

[lints]
workspace = true
